CREATE TABLE atendimentos (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    data_registro DATE,
    pedido_ruvolo VARCHAR(50),
    pedido_bees VARCHAR(50),
    numero_da_nf VARCHAR(50),
    valor_pedido_s_imp NUMERIC(12, 2),
    valor_nf_c_imp NUMERIC(12, 2),
    data_do_pedido DATE,
    itens_do_pedido TEXT,
    saida_do_pedido DATE,
    tipo_de_compra VARCHAR(50),
    vendedor VARCHAR(100),
    ususario_sys VARCHAR(100),
    canal VARCHAR(50),
    cod_cliente VARCHAR(50),
    cliente VARCHAR(255),
    cnpj VARCHAR(20),
    uf CHAR(2),
    cidade VARCHAR(100),
    bairro VARCHAR(100),
    endereco VARCHAR(255),
    num VARCHAR(10),
    cep VARCHAR(15),
    tel_alternativo VARCHAR(20),
    contato_com VARCHAR(100),
    "e-mail_1" VARCHAR(255),
    "e-mail_2" VARCHAR(255),
    cod_transp VARCHAR(50),
    transp VARCHAR(100),
    cnpj_transp VARCHAR(20),
    tipo_de_frete VARCHAR(50),
    conseguiu_contato TEXT,
    recebeu_boleto BOOLEAN,
    houve_reclamacao TEXT,
    processo_de_ocorrencia TEXT,
    criticidade VARCHAR(50),
    temperamento VARCHAR(50),
    preferência_por_canal VARCHAR(50),
    houve_elogio TEXT,
    houve_sugestao TEXT,
    resumo_da_conversa TEXT,
    nota_0_a_10 INTEGER CHECK (nota_0_a_10 BETWEEN 0 AND 10),
    enviou_o_boleto BOOLEAN
);
