CREATE TABLE vendas_db (
    id                  SERIAL PRIMARY KEY,     
    ven_pedido              VARCHAR(20),
    ven_pedido_bees         VARCHAR(20),
    ven_nf                  VARCHAR(15),
    ven_dt_nf               DATE,
    ven_vr_total            NUMERIC(12, 2),
    ven_vr_liq              NUMERIC(12, 2),
    ven_dt_digita           DATE,
    ven_hr_digita           TIME,
    ven_cod_pagto           VARCHAR(10),
    ven_pagto               VARCHAR(50),
    ven_lib_credit          DATE,
    ven_cod_tipo            VARCHAR(10),
    ven_tipo                VARCHAR(50),
    ven_cod_etapa           VARCHAR(10),
    ven_n_etapa             INTEGER,
    ven_etapa               VARCHAR(50),
    ven_dt_lib_etapa        DATE,
    ven_status              VARCHAR(20),
    ven_id_repres           VARCHAR(10),
    ven_user_repres         VARCHAR(50),
    ven_representante       VARCHAR(50),
    ven_canal_venda         VARCHAR(30),
    ven_cli_cod             VARCHAR(20),
    ven_cli_razao           VARCHAR(100),
    ven_cli_cnpj            VARCHAR(18),
    ven_cod_grupo           VARCHAR(20),
    ven_grupo_econ          VARCHAR(100),
    ven_tel_1               VARCHAR(20),
    ven_tel_2               VARCHAR(20),
    ven_tel_3               VARCHAR(20),
    ven_tel_4               VARCHAR(20),
    ven_email_princ         VARCHAR(100),
    ven_email_cob           VARCHAR(100),
    ven_endereco            VARCHAR(100),
    ven_num                 VARCHAR(10),
    ven_bairro              VARCHAR(50),
    ven_cidade              VARCHAR(50),
    ven_uf                  CHAR(2),
    ven_cep                 VARCHAR(10),
    ven_dt_saida            DATE,
    ven_cif_fob             VARCHAR(10),
    ven_cod_transp          VARCHAR(20),
    ven_transp              VARCHAR(100),
    ven_transp_fantasia     VARCHAR(100),
    ven_transp_cnpj         VARCHAR(18),
    ven_produtos_nf         TEXT
);
